services:
  mysql:
    image: mysql:8.0.44
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arturka1
      MYSQL_DATABASE: products_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  userservice:
    build: ./UserService
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=users_db;User=root;Password=arturka1;SslMode=None;"
    depends_on:
      - mysql

  productservice:
    build: ./ProductService
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=products_db;User=root;Password=arturka1;SslMode=None;"
    depends_on:
      - mysql

volumes:
  mysql_data: